---
- name: Create folder for "collectd"
  file:
    path: "{{ dse_mc_collectd_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ dse_svc_user }}"
    group: "{{ dse_svc_user }}"

- name: Create prometheus.conf file within "collectd" directory
  copy:
    dest: "{{ dse_mc_collectd_dir }}/{{ dse_prom_conf_file }}"
    owner: "{{ dse_svc_user }}"
    group: "{{ dse_svc_user }}"
    content: |
        LoadPlugin write_prometheus
        
        <Plugin write_prometheus>
          Port "{{ prom_collectd_listening_port }}"
        </Plugin>

- name: Get PID information the running running DSE service
  shell: "ps -ef | grep cassandra | grep -v grep | grep -v collectd | awk '{print $2}'"
  register: dse_process_shell_output

- name: Set DSE PID to a variable
  set_fact: dse_pid="{{ dse_process_shell_output.stdout }}"

#- debug: msg="{{ dse_pid }}"

- name: Stop proceeding further if there is no active DSE service
  fail: msg="DSE is not running. Please start DSE first!"
  when: "dse_pid|length == 0"

#
## Disable and re-enable DSE metrics collector in order to make effective collectd prometheus configruation changes
#
- name: Disable DSE metrics collector
  shell: dsetool insights_config --mode DISABLED

- name: Enable DSE metrics collector
  shell: dsetool insights_config --mode ENABLED_WITH_LOCAL_STORAGE

#
# Check if DSE metrics collector is listening on port "{{ prom_collectd_listening_port }}"
#
- name: Get DSE metrics collector listening port information
  shell: "netstat -ntlp | grep 9103 | awk -F':' '{print $4}' | sed 's/ //g'"
  register: listening_port_shell_output

- name: Set DSE metrics collector listening port to a variable
  set_fact: detected_listening_port="{{ listening_port_shell_output.stdout }}"

#- debug: msg="{{ detected_listening_port }}"

- name: Stop proceeding further if there is no proper DSE metrics collector listening port
  fail: msg="DSE metrics collector is detected listening on port {{ detected_listening_port }} (expecting port {{ prom_collectd_listening_port }})!"
  when: detected_listening_port|int != prom_collectd_listening_port|int

- name: Get DSE cluster name information
  run_once: true
  shell: |
    nodetool describecluster | head -2 | tail -1 | awk -F': ' '{print $2}'
  register: nt_desc_cluster_info
#- debug: msg={{ nt_desc_cluster_info }}
#  run_once: true

##
# NOTE: set_fact is local! 
#
- name: Set DSE cluster name to a global variable
  run_once: true
  set_fact: dse_cluster_name="{{ nt_desc_cluster_info.stdout }}"
#- debug: msg={{ dse_cluster_name }}
#  run_once: true

- name: Get DSE node list with Metrics Collector listening port
  run_once: true
  set_fact: dse_nodes_ips_with_mc_port="{% for host in groups['dse_server'] %}"{{ hostvars[host].ansible_eth0.ipv4.address }}:{{ prom_collectd_listening_port }}"{% if not loop.last %},{% endif %}{% endfor %}"
#- debug: msg={{ dse_nodes_ips_with_mc_port }}
#  run_once: true